<a href="https://colab.research.google.com/github/2403a52012-lgtm/AIAC/blob/main/Lab2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use Gemini in Colab to write a function that filters out all negative numbers from a
given list.
prompt: write a function that filters out all negative numbers from a list.

Ask Gemini to generate code that reads a text file and counts the frequency of each
word. Then ask it to explain the code.

prompt: generate a code that reads a text file and counts the frequency of each word.

In [ ]:
import re
from collections import Counter

def count_word_frequency(filepath):
  """
  Reads a text file and counts the frequency of each word.

  Args:
    filepath: The path to the text file.

  Returns:
    A dictionary where keys are words and values are their frequencies.
  """
  word_list = []
  try:
    with open(filepath, 'r', encoding='utf-8') as f:
      text = f.read().lower()
      # Use regex to find all words (sequences of letters)
      word_list = re.findall(r'\b[a-z]+\b', text)
  except FileNotFoundError:
    print(f"Error: File not found at {filepath}")
    return {}

  # Count word frequencies
  word_counts = Counter(word_list)
  return dict(word_counts)

# Create a dummy text file for demonstration
with open("sample_text.txt", "w", encoding="utf-8") as f:
    f.write("This is a sample text file.\n")
    f.write("This file is just a sample.")

# Example usage:
file_path = "sample_text.txt"
word_frequencies = count_word_frequency(file_path)
print(word_frequencies)

{'this': 2, 'is': 2, 'a': 2, 'sample': 2, 'text': 1, 'file': 2, 'just': 1}


def filter_negative_numbers(numbers):: This line defines a function named filter_negative_numbers that takes one argument, numbers, which is expected to be a list.
Docstring ("""Docstring goes here"""): This is a documentation string that explains what the function does, its arguments (Args), and what it returns (Returns). It's good practice to include docstrings to make your code understandable.
return [number for number in numbers if number >= 0]: This is the core of the function. It's a list comprehension, which is a concise way to create lists in Python.
for number in numbers: This iterates through each element in the input numbers list.
if number >= 0: This is a condition. For each number, it checks if the number is greater than or equal to 0 (i.e., not negative).
[number ...]: If the condition is True, the number is included in the new list being created.
The entire expression creates a new list containing only the numbers from the original list that met the condition (>= 0). This new list is then returned by the function.
# Example usage:: This is a comment indicating the start of example code demonstrating how to use the function.
my_list = [1, -2, 3, -4, 5, 0, -10]: This line creates a list named my_list containing both positive, negative, and zero values.
filtered_list = filter_negative_numbers(my_list): This line calls the filter_negative_numbers function with my_list as the input. The returned list (containing only the non-negative numbers) is stored in the variable filtered_list.
print(filtered_list): This line prints the contents of the filtered_list to the console. Based on the input my_list, the output will be [1, 3, 5, 0].
In summary, this code defines a function that efficiently creates a new list containing only the non-negative elements from an input list, and then demonstrates how to use this function with an example list.


Please explain this code:

I have already explained the selected code in my previous response. Do you have any other questions about it, or would you like to move on to something else?


Ask Gemini to generate code that reads a text file and counts the frequency of each word. Then ask it to explain the code.
Sure, I can help with that. First, I'll generate the code to read a text file and count the frequency of each word. I'll also include some example text to demonstrate its usage.

I have generated the code to count word frequencies from a text file and demonstrated its usage. Now, as you requested, I can explain how the code works. Would you like me to do that?


Please explain this code:

Certainly, I can explain the selected code.

The selected code defines a Python function count_word_frequency that takes a file path as input and returns a dictionary containing the frequency of each word in the file.

Here's a breakdown:

import re and from collections import Counter: These lines import the necessary libraries. re is used for regular expressions to find words, and Counter is a convenient class for counting hashable objects.
def count_word_frequency(filepath):: This defines the function count_word_frequency which accepts one argument, filepath.
Docstring: The triple-quoted string explains what the function does, its arguments (filepath), and what it returns (a dictionary of word frequencies).
word_list = []: Initializes an empty list to store the words found in the file.
try...except FileNotFoundError: This block attempts to open and read the file. If the file is not found, it catches the FileNotFoundError, prints an error message, and returns an empty dictionary.
with open(filepath, 'r', encoding='utf-8') as f:: This opens the file specified by filepath in read mode ('r') with UTF-8 encoding. The with statement ensures the file is automatically closed even if errors occur.
text = f.read().lower(): Reads the entire content of the file into the text variable and converts it to lowercase to ensure case-insensitive word counting.
word_list = re.findall(r'\b[a-z]+\b', text): This is where regular expressions are used.
re.findall() finds all occurrences of a pattern in a string.
r'\b[a-z]+\b' is the regular expression pattern:
\b: Matches a word boundary. This ensures that "the" in "there" is not matched as a whole word.
[a-z]+: Matches one or more lowercase letters.
\b: Matches another word boundary.
This effectively extracts sequences of lowercase letters that are whole words and stores them in word_list.
word_counts = Counter(word_list): Creates a Counter object from the word_list. The Counter automatically counts the occurrences of each unique word.
return dict(word_counts): Converts the Counter object back into a regular dictionary and returns it.
# Create a dummy text file for demonstration: This is a comment indicating the creation of a temporary file.
with open("sample_text.txt", "w", encoding="utf-8") as f:: This creates or opens a file named sample_text.txt in write mode ('w') with UTF-8 encoding.
f.write(...): These lines write sample text into the sample_text.txt file.
# Example usage:: Comment indicating the start of the example.
file_path = "sample_text.txt": Sets the file_path variable to the name of the dummy file.
word_frequencies = count_word_frequency(file_path): Calls the count_word_frequency function with the dummy file path and stores the resulting word frequency dictionary in word_frequencies.
print(word_frequencies): Prints the word_frequencies dictionary to the console, showing the count of each word in the sample text.
In summary, the code defines a reusable function to count word frequencies in any given text file and provides a simple example demonstrating how to use it with a temporary file.



Use Cursor AI to generate a Python class called Book with attributes title, author, and
a method summary() that prints the details.
prompt: Generate a python class Book with attributes title, author,and a method summuary()that prints the details.

In [ ]:
class Book:
  """
  Represents a book with title and author.
  """
  def __init__(self, title, author):
    """
    Initializes a Book object.

    Args:
      title: The title of the book.
      author: The author of the book.
    """
    self.title = title
    self.author = author

  def summary(self):
    """
    Prints the details of the book.
    """
    print(f"Title: {self.title}")
    print(f"Author: {self.author}")

# Example usage:
my_book = Book("The Hitchhiker's Guide to the Galaxy", "Douglas Adams")
my_book.summary()

Title: The Hitchhiker's Guide to the Galaxy
Author: Douglas Adams


class Book:: This line defines a new class named Book. Classes are blueprints for creating objects (instances).
""" Represents a book with title and author. """: This is a docstring for the class. It explains the purpose of the Book class.
def __init__(self, title, author):: This is the constructor method of the class. It's a special method that is automatically called when you create a new Book object.
self: Refers to the instance of the class itself.
title and author: These are parameters that you pass when creating a Book object (e.g., the title and author of the book).
The docstring within __init__ explains its purpose and arguments.
self.title = title and self.author = author: These lines assign the values passed for title and author to the title and author attributes of the Book object.
def summary(self):: This defines a method within the Book class called summary. Methods are functions that belong to a class and operate on the class's objects.
self: Again, refers to the instance of the class.
The docstring for summary explains that it prints the details of the book.
print(f"Title: {self.title}") and print(f"Author: {self.author}"): These lines use f-strings to print the title and author attributes of the specific Book object on which the summary method is called.
# Example usage:: This is a comment indicating the start of example code.
my_book = Book("The Hitchhiker's Guide to the Galaxy", "Douglas Adams"): This line creates an instance (an object) of the Book class. It calls the __init__ method with the title "The Hitchhiker's Guide to the Galaxy" and the author "Douglas Adams". This creates a Book object named my_book with these attributes.
my_book.summary(): This line calls the summary method on the my_book object. This will execute the code inside the summary method for the my_book instance, printing its title and author.
In essence, this code defines a simple structure for representing books and provides a way to display their key information.



Ask Gemini to write a program that checks whether a number is an Armstrong
number, and then modify it using Cursor AI to improve performance or structure.
Prompt:write a program that checks wheather a numberis a armstrong number,and then modify it is using Cursor AI to improve performance or structure.

In [ ]:
def is_armstrong_number(number):
  """
  Checks if a number is an Armstrong number.

  An Armstrong number (or narcissistic number) is a number that is the sum of
  its own digits each raised to the power of the number of digits.

  Args:
    number: An integer.

  Returns:
    True if the number is an Armstrong number, False otherwise.
  """
  # Convert the number to a string to get the number of digits
  num_str = str(number)
  num_digits = len(num_str)

  # Calculate the sum of each digit raised to the power of the number of digits
  armstrong_sum = 0
  for digit in num_str:
    armstrong_sum += int(digit) ** num_digits

  # Check if the sum equals the original number
  return armstrong_sum == number

# Example usage:
num_to_check = 153
if is_armstrong_number(num_to_check):
  print(f"{num_to_check} is an Armstrong number")
else:
  print(f"{num_to_check} is not an Armstrong number")

num_to_check = 123
if is_armstrong_number(num_to_check):
  print(f"{num_to_check} is an Armstrong number")
else:
  print(f"{num_to_check} is not an Armstrong number")

153 is an Armstrong number
123 is not an Armstrong number


This code snippet contains the implementation of the is_armstrong_number function and examples of how to use it.

Here's a breakdown:

Docstring (""" ... """): This part of the code is a docstring that explains the function's purpose, its arguments (Args), and what it returns (Returns). It clarifies that the function checks if a given integer is an Armstrong number.
num_str = str(number): This line converts the input number into a string. This is done to easily determine the number of digits in the number and to iterate through each digit.
num_digits = len(num_str): This line calculates the number of digits in the number by getting the length of the string representation.
armstrong_sum = 0: Initializes a variable armstrong_sum to 0. This variable will store the sum of each digit raised to the power of the total number of digits.
for digit in num_str:: This loop iterates through each character (which is a digit) in the num_str string.
armstrong_sum += int(digit) ** num_digits: Inside the loop, for each digit:
int(digit): Converts the digit character back into an integer.
** num_digits: Raises the integer value of the digit to the power of num_digits (the total number of digits in the original number).
armstrong_sum += ...: Adds the result to the armstrong_sum.
return armstrong_sum == number: After the loop finishes, this line checks if the calculated armstrong_sum is equal to the original number. If they are equal, the function returns True, indicating that the number is an Armstrong number. Otherwise, it returns False.
# Example usage:: This is a comment indicating the start of example code that demonstrates how to use the is_armstrong_number function.
num_to_check = 153: Sets a variable num_to_check to the value 153.
if is_armstrong_number(num_to_check): ... else: ...: This is an if-else block that calls the is_armstrong_number function with num_to_check. Based on the boolean value returned by the function, it prints whether 153 is an Armstrong number or not.
num_to_check = 123: Sets the num_to_check variable to 123 for another example.
if is_armstrong_number(num_to_check): ... else: ...: Another if-else block that checks and prints whether 123 is an Armstrong number.
In summary, the selected code defines the logic for identifying an Armstrong number by summing the digits raised to the power of the number of digits and then provides clear examples of how to test the function with different numbers.












Use both Gemini and Cursor AI to generate code for sorting a list of dictionaries by a
specific key (e.g., age).
Prompt: Generate code for sorting a list of dictionaries by a specific key (e.g., age).

In [ ]:
def sort_list_of_dicts(list_of_dicts, key):
  """
  Sorts a list of dictionaries by a specific key.

  Args:
    list_of_dicts: The list of dictionaries to sort.
    key: The key to sort by.

  Returns:
    A new list of dictionaries sorted by the specified key.
  """
  return sorted(list_of_dicts, key=lambda x: x[key])

# Example usage:
data = [
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 25},
    {"name": "Charlie", "age": 35},
    {"name": "David", "age": 25},
]

sorted_data = sort_list_of_dicts(data, key="age")
print(sorted_data)

[{'name': 'Bob', 'age': 25}, {'name': 'David', 'age': 25}, {'name': 'Alice', 'age': 30}, {'name': 'Charlie', 'age': 35}]


Certainly, I can explain the selected code.

This code defines a Python function sort_list_of_dicts that sorts a list of dictionaries based on the value associated with a specified key, and then provides an example of how to use it.

Here's a breakdown:

def sort_list_of_dicts(list_of_dicts, key):: This line defines a function named sort_list_of_dicts that takes two arguments:
list_of_dicts: The list of dictionaries that you want to sort.
key: The key within each dictionary that you want to use as the basis for sorting.
Docstring (""" ... """): This is a docstring that explains the function's purpose, its arguments (Args), and what it returns (Returns).
return sorted(list_of_dicts, key=lambda x: x[key]): This is the core of the sorting logic.
sorted(): This is a built-in Python function that returns a new sorted list from the items in an iterable. It does not modify the original list.
list_of_dicts: This is the list that sorted() will operate on.
key=lambda x: x[key]: This is the crucial part that tells sorted() how to sort the list.
key= : This argument specifies a function to be called on each list element prior to making comparisons.
lambda x: x[key]: This is a small, anonymous function (a lambda function).
lambda x:: Defines a simple function that takes one argument, x. In this context, x will represent each dictionary in the list_of_dicts as sorted() iterates through it.
x[key]: This accesses the value associated with the specified key within the current dictionary (x).
So, for each dictionary in the list, the sorted() function will use the value of the specified key to determine the sorting order. The function then returns the newly sorted list.
# Example usage:: This is a comment indicating the start of example code.
data = [...]: This defines a sample list of dictionaries named data. Each dictionary represents a person with "name" and "age".
sorted_data = sort_list_of_dicts(data, key="age"): This line calls the sort_list_of_dicts function with the data list and the key "age". The function sorts the data list based on the "age" value in each dictionary, and the resulting sorted list is stored in the sorted_data variable.
print(sorted_data): This line prints the contents of the sorted_data list to the console, showing the dictionaries sorted by age.


In [3]:
def filter_negative_numbers(numbers):
  """
  Filters out all negative numbers from a list.

  Args:
    numbers: A list of numbers.

  Returns:
    A new list containing only the non-negative numbers from the input list.
  """
  return [number for number in numbers if number >= 0]

# Example usage:
my_list = [1, -2, 3, -4, 5, 0, -10]
filtered_list = filter_negative_numbers(my_list)
print(filtered_list)

[1, 3, 5, 0]


his code snippet defines a Python function called filter_negative_numbers that takes a list of numbers as input and returns a new list containing only the non-negative numbers from the original list.

Here's a breakdown:

def filter_negative_numbers(numbers):: This line defines the function named filter_negative_numbers that accepts one argument, numbers, which is expected to be a list.
Docstring ("""Docstring goes here"""): This is a documentation string that explains what the function does, its arguments (Args), and what it returns (Returns). It's good practice to include docstrings to make your code understandable.
return [number for number in numbers if number >= 0]: This is the core of the function. It's a list comprehension, which is a concise way to create lists in Python.
for number in numbers: This iterates through each element in the input numbers list.
if number >= 0: This is a condition. For each number, it checks if the number is greater than or equal to 0 (i.e., not negative).
[number ...]: If the condition is True, the number is included in the new list being created. The entire expression creates a new list containing only the numbers from the original list that met the condition (>= 0). This new list is then returned by the function.
# Example usage:: This is a comment indicating the start of example code demonstrating how to use the function.
my_list = [1, -2, 3, -4, 5, 0, -10]: This line creates a list named my_list containing both positive, negative, and zero values.
filtered_list = filter_negative_numbers(my_list): This line calls the filter_negative_numbers function with my_list as the input. The returned list (containing only the non-negative numbers) is stored in the variable filtered_list.
print(filtered_list): This line prints the contents of the filtered_list to the console. Based on the input my_list, the output will be [1, 3, 5, 0].
In summary, this code defines a function that efficiently creates a new list containing only the non-negative elements from an input list, and then demonstrates how to use this function with an example list.

What can I help you build?
0 / 2000
Gemini can make mistakes so double-check it and use code with caution. Learn more